name: Trading Scanner
on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

permissions:
  contents: write  # This is crucial for push access

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # This provides the necessary permissions

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install axios --no-package-lock --no-save

      - name: Create data directory
        run: mkdir -p data

      - name: Run scanner
        run: node fetch.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git diff-index --quiet HEAD || git commit -m "Update scan results"
          git push
