name: Trading Scanner
on:
  schedule:
    - cron: '*/10 7-20 * * *'  # Every 10 min 08:00-21:00 BST
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install axios technicalindicators cheerio
          
      - name: Run scanner
        run: node fetch.js
        
      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Automatic scan update" || echo "No changes"
          git push
