name: Trading Scanner
on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies directly
        run: |
          npm init -y
          npm install axios technicalindicators --no-package-lock --no-save

      - name: Create data directory
        run: mkdir -p data

      - name: Run scanner
        run: node fetch.js

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Update scan results" || echo "No changes to commit"
          git push
